//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sky_Wings_Airline.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.Passenger_List = new HashSet<Passenger_List>();
        }
    
        public int ID { get; set; }
        public int IDDepartureAirport { get; set; }
        public int IDArrivalAirport { get; set; }
        public int IDPlane { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> IDPrice { get; set; }
        public int IDStatus { get; set; }
        public int IDFirstPilot { get; set; }
        public int IDSecondPilot { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual Flight_Attendant_List Flight_Attendant_List { get; set; }
        public virtual Planes Planes { get; set; }
        public virtual Price Price { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger_List> Passenger_List { get; set; }
    }
}
